baseURL: "https://n5cent28.github.io/"
title: "Noah Nicol"
theme: "PaperMod"
languageCode: "en-us"
pagination:
  pagerSize: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Noah Nicol
  description: "Personal website and blog"
  keywords: [Blog, Portfolio, PaperMod]
  author: Noah Nicol

  images: ["images/profile.jpg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  ShowToc: true
  TocOpen: true

  profileMode:
    enabled: true
    title: "Noah Nicol"
    subtitle: "Bioinformatic Scientist"
    imageUrl: "images/profile.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: "Noah Nicol"
    buttons:
      - name: about
        url: /about/
      - name: resume
        url: /resume/
      - name: projects
        url: /projects
      - name: hobbies
        url: /hobbies

  socialIcons:
    - name: github
      url: "https://github.com/N5cent28"
    - name: linkedin
      url: "https://www.linkedin.com/in/noah-nicol-2a0163144/"
      

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: resume
      name: Resume
      url: /resume/
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 30
    - identifier: hobbies
      name: Hobbies
      url: /hobbies/
      weight: 40

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
